language: c

env:
  matrix:
    - python=2.6  CONDA_PY=26  CONDA_NPY=18
    - python=2.7  CONDA_PY=27  CONDA_NPY=18
    - python=3.3  CONDA_PY=33  CONDA_NPY=18
    - python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    - secure: "VbVG6isXjRCZeBu9J9NW5xosGfQlHKcuBkjmb8vc2drGjNMP7UctGo5O4fTdF4i70irqfQSUlVGWhgu+OFk4PZ/YadlMydG9z2tF9n0mYzrWxWBmb1EZBcHmwCdG+o52GBWD3VVHOggygx2uFIJJyQCEFHkyU4fdhVnhA+LZeq4="

install:
  - source continuous-integration/travis/install.sh
  - conda build conda-recipe --no-test --quiet

script:
  - conda build conda-recipe --test --quiet

after_success:
  - ls $(conda build conda-recipe --output)
  - binstar -t $BINSTAR_TOKEN upload --force $(conda build conda-recipe --output)
