package:
  name: pyappveyordemo
  version: !!str dev

requirements:
  build:
    - cython
    - numpy
    - setuptools

  run:
    - numpy

test:
    requires:
        - nose
    commands:
        - nosetests --exe pyappveyordemo

about:
  home: https://github.com/rmcgibbo/python-appveyor-conda-example
  license: MIT